version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  db: # название моего имеджа
    restart: always
    image: postgres:12 # скачает image postgres 12 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports: # порты
      - "5432:5432"
    environment: # переменные окружения, меняйте их если хотите поменять пароль, логин или название стартовой базы данных
      POSTGRES_USER: dev_user
      POSTGRES_DB: dev_db
      POSTGRES_PASSWORD: dev_pass
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  grafana-data:
    driver: local