---


listener:
  address: :8090

bot:
  token: vk1.a.uFRpa2habq8Rmw33Zyrm07JHYnFE5XfftT185wonHkpsHObhKA7-Imwrw00zkeZLhXe9z6ofxX5YUPDZsYL8bnTSs_QX06LRn2I3LGnKtPyoPURTky1YgCruJuyn7Kn80eMsppjB__AhyN9Ka7v3J_z4mnpvUIcDfQeBjJCe5VruAsWv2ugEJQxpoK-4DkSNG7Qy5X59ZJuCQz7XFIqAVA
  user_token: vk1.a.6TH9MWp-WkluPLqpqf2TlFP6MkMrp_7b70G8acMbdJhelZyU_FxycX7nI2JFkrXT9RjLPz3NnYvUKeU0esE563yk9km2uj39HijeOqssUn5zh4Kn-QEYj8JqrRkCJ1lA5u5RH0AuLTVRDIhPNu8kghvrnFU-gPYW2rfpIZfnoE9fCDKxq5qnJfcRYHazm9vV5tbYCGxgQ7CDf7E6pUqsKw
  group_id: 225171132
clients:
  postgres:
    name: dev_db
    port: 5432
    user: dev_user
    pass: dev_pass
    host: localhost

#vk1.a.6TH9MWp-WkluPLqpqf2TlFP6MkMrp_7b70G8acMbdJhelZyU_FxycX7nI2JFkrXT9RjLPz3NnYvUKeU0esE563yk9km2uj39HijeOqssUn5zh4Kn-QEYj8JqrRkCJ1lA5u5RH0AuLTVRDIhPNu8kghvrnFU-gPYW2rfpIZfnoE9fCDKxq5qnJfcRYHazm9vV5tbYCGxgQ7CDf7E6pUqsKw